<!-- 
Copyright 1999 Jason Abbott (jabbott@uidaho.edu)
08/27/1998: created page
08/28/1998: made dark to light wood blend; adjusted text position
-->

	</td>
	<td valign="top" background="/hosted/akc/wood01.jpg"><hr size="1" color="#000000">
	<font face="arial" size=2><b>
	<ul>
	<li><a href="/hosted/akc/default.asp">Home</a>
	<li>Photo Gallery
	<li><a href="/hosted/akc/samples/samples.asp">Samples</a>
	<li>Tips
	<li><a href="/hosted/akc/community/community.asp">Community</a>
	<li><a href="/hosted/akc/history/history.asp">History</a>
	</ul>
	</td>
<tr>
	<td height="20" background="/hosted/akc/wood01a.jpg">&nbsp;</td>
<tr>
	<td height="20" background="/hosted/akc/wood01b.jpg">&nbsp;</td>
<tr>
	<td height="20" background="/hosted/akc/wood01c.jpg">&nbsp;</td>
<tr>
	<td align="center"><hr size="1" color="#000000"></td>
	<td height="20" background="/hosted/akc/wood01d.jpg"><hr size="1" color="#000000"></td>
<tr>
	<td align="center" rowspan=3 valign="bottom">
	<i>Where the three year written warranty is standard</i>
	<p>
	<font size=1 face="arial">
	Copyright &copy; 1998 Abbott Kitchen Center.  All Rights Reserved.<br>
	This site was created by <a href="http://www.uidaho.edu/~jabbott" target="_top">Jason Abbott</a> (<a href="mailto:jabbott@uidaho.edu">jabbott@uidaho.edu</a>)
	</font></td>
	<td height="20" background="/hosted/akc/wood01e.jpg">&nbsp;</td>
<tr>
	<td height="20" background="/hosted/akc/wood01f.jpg">&nbsp;</td>
<tr>
	<td height="20" background="/hosted/akc/wood01g.jpg">&nbsp;</td>
</table>
</body>
</html>