<!-- 
Copyright 1999 Jason Abbott (jabbott@uidaho.edu)
08/27/98: created page
-->

<html>
<head>
<title>Abbott Kitchen Center</title>
</head>
<body bgcolor="#FFFFFF" leftmargin=2 topmargin=2 link="#443322" vlink="#443322">
<table border="0" cellspacing="0" cellpadding="3" width="100%">
<tr>
	<td><img src="/hosted/akc/akc_logo.jpeg" width=233 height=113 border="0"></td>
	<td width="150" align="right" background="/hosted/akc/wood01.jpg"><font face="arial" size=2><b>
	2305 South Main<br>
	P.O. Box 9312<br>
	Moscow, Idaho  83843<br>
	(208) 883-4931<br>
	<a href="mailto:akc@moscow.com">akc@moscow.com</a>
	</b></font></td>
<tr>
	<td valign="top" rowspan=4><hr size="1" color="#000000">